[package]
name = "relm-backend"
version = "0.1.0"
edition = "2018"

[lib]
name = "backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module"] }
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.4.1"
numpy = "0.27.1"
rug = "1.11.0"
ndarray = "0.17.2"
